//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package models

import "errors"

type DestinationEngine string

const (
	DestinationEngine_Mysql      DestinationEngine = "mysql"
	DestinationEngine_Postgresql DestinationEngine = "postgresql"
)

var DestinationEngineAllValues = []DestinationEngine{
	DestinationEngine_Mysql,
	DestinationEngine_Postgresql,
}

func (e *DestinationEngine) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "mysql":
		*e = DestinationEngine_Mysql
	case "postgresql":
		*e = DestinationEngine_Postgresql
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for DestinationEngine enum")
	}

	return nil
}

func (e DestinationEngine) String() string {
	return string(e)
}
