//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package models

import "errors"

type SourceEngine string

const (
	SourceEngine_Mysql      SourceEngine = "mysql"
	SourceEngine_Postgresql SourceEngine = "postgresql"
)

var SourceEngineAllValues = []SourceEngine{
	SourceEngine_Mysql,
	SourceEngine_Postgresql,
}

func (e *SourceEngine) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "mysql":
		*e = SourceEngine_Mysql
	case "postgresql":
		*e = SourceEngine_Postgresql
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for SourceEngine enum")
	}

	return nil
}

func (e SourceEngine) String() string {
	return string(e)
}
