//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package models

import (
	"time"

	"github.com/google/uuid"
)

type Tags struct {
	TenantID        uuid.UUID `sql:"primary_key"`
	TagID           uuid.UUID `sql:"primary_key"`
	Key             *string
	Value           *string
	CreatedByUserID *uuid.UUID
	UpdatedByUserID *uuid.UUID
	CreatedAt       *time.Time
	UpdatedAt       *time.Time
}
