//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package models

import "errors"

type Tier string

const (
	Tier_FreeTrial Tier = "free_trial"
	Tier_Bronze    Tier = "bronze"
	Tier_Silver    Tier = "silver"
	Tier_Gold      Tier = "gold"
	Tier_Platinum  Tier = "platinum"
)

var TierAllValues = []Tier{
	Tier_FreeTrial,
	Tier_Bronze,
	Tier_Silver,
	Tier_Gold,
	Tier_Platinum,
}

func (e *Tier) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "free_trial":
		*e = Tier_FreeTrial
	case "bronze":
		*e = Tier_Bronze
	case "silver":
		*e = Tier_Silver
	case "gold":
		*e = Tier_Gold
	case "platinum":
		*e = Tier_Platinum
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Tier enum")
	}

	return nil
}

func (e Tier) String() string {
	return string(e)
}
