//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package models

import "errors"

type TopicProducerType string

const (
	TopicProducerType_Source      TopicProducerType = "source"
	TopicProducerType_Transformer TopicProducerType = "transformer"
)

var TopicProducerTypeAllValues = []TopicProducerType{
	TopicProducerType_Source,
	TopicProducerType_Transformer,
}

func (e *TopicProducerType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "source":
		*e = TopicProducerType_Source
	case "transformer":
		*e = TopicProducerType_Transformer
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for TopicProducerType enum")
	}

	return nil
}

func (e TopicProducerType) String() string {
	return string(e)
}
