//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package models

import (
	"time"

	"github.com/google/uuid"
)

type Topics struct {
	TenantID     uuid.UUID `sql:"primary_key"`
	TopicID      uuid.UUID `sql:"primary_key"`
	Name         *string
	ProducerType *TopicProducerType
	ProducerID   *uuid.UUID
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
}
