//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package models

import (
	"time"

	"github.com/google/uuid"
)

type TransformerInputs struct {
	TenantID      uuid.UUID `sql:"primary_key"`
	TransformerID uuid.UUID `sql:"primary_key"`
	TopicID       uuid.UUID `sql:"primary_key"`
	Config        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
