//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Destination = newDestinationTable("public", "destination", "")

type destinationTable struct {
	postgres.Table

	// Columns
	TenantID        postgres.ColumnString
	DestinationID   postgres.ColumnString
	Name            postgres.ColumnString
	Engine          postgres.ColumnString
	Config          postgres.ColumnString
	CreatedByUserID postgres.ColumnString
	UpdatedByUserID postgres.ColumnString
	CreatedAt       postgres.ColumnTimestamp
	UpdatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DestinationTable struct {
	destinationTable

	EXCLUDED destinationTable
}

// AS creates new DestinationTable with assigned alias
func (a DestinationTable) AS(alias string) *DestinationTable {
	return newDestinationTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DestinationTable with assigned schema name
func (a DestinationTable) FromSchema(schemaName string) *DestinationTable {
	return newDestinationTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DestinationTable with assigned table prefix
func (a DestinationTable) WithPrefix(prefix string) *DestinationTable {
	return newDestinationTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DestinationTable with assigned table suffix
func (a DestinationTable) WithSuffix(suffix string) *DestinationTable {
	return newDestinationTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDestinationTable(schemaName, tableName, alias string) *DestinationTable {
	return &DestinationTable{
		destinationTable: newDestinationTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newDestinationTableImpl("", "excluded", ""),
	}
}

func newDestinationTableImpl(schemaName, tableName, alias string) destinationTable {
	var (
		TenantIDColumn        = postgres.StringColumn("tenant_id")
		DestinationIDColumn   = postgres.StringColumn("destination_id")
		NameColumn            = postgres.StringColumn("name")
		EngineColumn          = postgres.StringColumn("engine")
		ConfigColumn          = postgres.StringColumn("config")
		CreatedByUserIDColumn = postgres.StringColumn("created_by_user_id")
		UpdatedByUserIDColumn = postgres.StringColumn("updated_by_user_id")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		allColumns            = postgres.ColumnList{TenantIDColumn, DestinationIDColumn, NameColumn, EngineColumn, ConfigColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, EngineColumn, ConfigColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns        = postgres.ColumnList{}
	)

	return destinationTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:        TenantIDColumn,
		DestinationID:   DestinationIDColumn,
		Name:            NameColumn,
		Engine:          EngineColumn,
		Config:          ConfigColumn,
		CreatedByUserID: CreatedByUserIDColumn,
		UpdatedByUserID: UpdatedByUserIDColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
