//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Destinations = newDestinationsTable("public", "destinations", "")

type destinationsTable struct {
	postgres.Table

	// Columns
	TenantID        postgres.ColumnString
	DestinationID   postgres.ColumnString
	Name            postgres.ColumnString
	Engine          postgres.ColumnString
	Config          postgres.ColumnString
	CreatedByUserID postgres.ColumnString
	UpdatedByUserID postgres.ColumnString
	CreatedAt       postgres.ColumnTimestamp
	UpdatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DestinationsTable struct {
	destinationsTable

	EXCLUDED destinationsTable
}

// AS creates new DestinationsTable with assigned alias
func (a DestinationsTable) AS(alias string) *DestinationsTable {
	return newDestinationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DestinationsTable with assigned schema name
func (a DestinationsTable) FromSchema(schemaName string) *DestinationsTable {
	return newDestinationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DestinationsTable with assigned table prefix
func (a DestinationsTable) WithPrefix(prefix string) *DestinationsTable {
	return newDestinationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DestinationsTable with assigned table suffix
func (a DestinationsTable) WithSuffix(suffix string) *DestinationsTable {
	return newDestinationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDestinationsTable(schemaName, tableName, alias string) *DestinationsTable {
	return &DestinationsTable{
		destinationsTable: newDestinationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newDestinationsTableImpl("", "excluded", ""),
	}
}

func newDestinationsTableImpl(schemaName, tableName, alias string) destinationsTable {
	var (
		TenantIDColumn        = postgres.StringColumn("tenant_id")
		DestinationIDColumn   = postgres.StringColumn("destination_id")
		NameColumn            = postgres.StringColumn("name")
		EngineColumn          = postgres.StringColumn("engine")
		ConfigColumn          = postgres.StringColumn("config")
		CreatedByUserIDColumn = postgres.StringColumn("created_by_user_id")
		UpdatedByUserIDColumn = postgres.StringColumn("updated_by_user_id")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		allColumns            = postgres.ColumnList{TenantIDColumn, DestinationIDColumn, NameColumn, EngineColumn, ConfigColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, EngineColumn, ConfigColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns        = postgres.ColumnList{}
	)

	return destinationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:        TenantIDColumn,
		DestinationID:   DestinationIDColumn,
		Name:            NameColumn,
		Engine:          EngineColumn,
		Config:          ConfigColumn,
		CreatedByUserID: CreatedByUserIDColumn,
		UpdatedByUserID: UpdatedByUserIDColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
