//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PipelineTransformerInputs = newPipelineTransformerInputsTable("public", "pipeline_transformer_inputs", "")

type pipelineTransformerInputsTable struct {
	postgres.Table

	// Columns
	TenantID      postgres.ColumnString
	PipelineID    postgres.ColumnString
	TransformerID postgres.ColumnString
	TopicID       postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PipelineTransformerInputsTable struct {
	pipelineTransformerInputsTable

	EXCLUDED pipelineTransformerInputsTable
}

// AS creates new PipelineTransformerInputsTable with assigned alias
func (a PipelineTransformerInputsTable) AS(alias string) *PipelineTransformerInputsTable {
	return newPipelineTransformerInputsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PipelineTransformerInputsTable with assigned schema name
func (a PipelineTransformerInputsTable) FromSchema(schemaName string) *PipelineTransformerInputsTable {
	return newPipelineTransformerInputsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PipelineTransformerInputsTable with assigned table prefix
func (a PipelineTransformerInputsTable) WithPrefix(prefix string) *PipelineTransformerInputsTable {
	return newPipelineTransformerInputsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PipelineTransformerInputsTable with assigned table suffix
func (a PipelineTransformerInputsTable) WithSuffix(suffix string) *PipelineTransformerInputsTable {
	return newPipelineTransformerInputsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPipelineTransformerInputsTable(schemaName, tableName, alias string) *PipelineTransformerInputsTable {
	return &PipelineTransformerInputsTable{
		pipelineTransformerInputsTable: newPipelineTransformerInputsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                       newPipelineTransformerInputsTableImpl("", "excluded", ""),
	}
}

func newPipelineTransformerInputsTableImpl(schemaName, tableName, alias string) pipelineTransformerInputsTable {
	var (
		TenantIDColumn      = postgres.StringColumn("tenant_id")
		PipelineIDColumn    = postgres.StringColumn("pipeline_id")
		TransformerIDColumn = postgres.StringColumn("transformer_id")
		TopicIDColumn       = postgres.StringColumn("topic_id")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{TenantIDColumn, PipelineIDColumn, TransformerIDColumn, TopicIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{}
	)

	return pipelineTransformerInputsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:      TenantIDColumn,
		PipelineID:    PipelineIDColumn,
		TransformerID: TransformerIDColumn,
		TopicID:       TopicIDColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
