//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PipelineTransformer = newPipelineTransformerTable("public", "pipeline_transformer", "")

type pipelineTransformerTable struct {
	postgres.Table

	// Columns
	TenantID      postgres.ColumnString
	PipelineID    postgres.ColumnString
	TransformerID postgres.ColumnString
	Stage         postgres.ColumnInteger
	Config        postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PipelineTransformerTable struct {
	pipelineTransformerTable

	EXCLUDED pipelineTransformerTable
}

// AS creates new PipelineTransformerTable with assigned alias
func (a PipelineTransformerTable) AS(alias string) *PipelineTransformerTable {
	return newPipelineTransformerTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PipelineTransformerTable with assigned schema name
func (a PipelineTransformerTable) FromSchema(schemaName string) *PipelineTransformerTable {
	return newPipelineTransformerTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PipelineTransformerTable with assigned table prefix
func (a PipelineTransformerTable) WithPrefix(prefix string) *PipelineTransformerTable {
	return newPipelineTransformerTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PipelineTransformerTable with assigned table suffix
func (a PipelineTransformerTable) WithSuffix(suffix string) *PipelineTransformerTable {
	return newPipelineTransformerTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPipelineTransformerTable(schemaName, tableName, alias string) *PipelineTransformerTable {
	return &PipelineTransformerTable{
		pipelineTransformerTable: newPipelineTransformerTableImpl(schemaName, tableName, alias),
		EXCLUDED:                 newPipelineTransformerTableImpl("", "excluded", ""),
	}
}

func newPipelineTransformerTableImpl(schemaName, tableName, alias string) pipelineTransformerTable {
	var (
		TenantIDColumn      = postgres.StringColumn("tenant_id")
		PipelineIDColumn    = postgres.StringColumn("pipeline_id")
		TransformerIDColumn = postgres.StringColumn("transformer_id")
		StageColumn         = postgres.IntegerColumn("stage")
		ConfigColumn        = postgres.StringColumn("config")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{TenantIDColumn, PipelineIDColumn, TransformerIDColumn, StageColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{StageColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{}
	)

	return pipelineTransformerTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:      TenantIDColumn,
		PipelineID:    PipelineIDColumn,
		TransformerID: TransformerIDColumn,
		Stage:         StageColumn,
		Config:        ConfigColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
