//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PipelineDestinationInputs = newPipelineDestinationInputsTable("public", "pipeline_destination_inputs", "")

type pipelineDestinationInputsTable struct {
	postgres.Table

	// Columns
	TenantID   postgres.ColumnString
	PipelineID postgres.ColumnString
	TopicID    postgres.ColumnString
	CreatedAt  postgres.ColumnTimestamp
	UpdatedAt  postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PipelineDestinationInputsTable struct {
	pipelineDestinationInputsTable

	EXCLUDED pipelineDestinationInputsTable
}

// AS creates new PipelineDestinationInputsTable with assigned alias
func (a PipelineDestinationInputsTable) AS(alias string) *PipelineDestinationInputsTable {
	return newPipelineDestinationInputsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PipelineDestinationInputsTable with assigned schema name
func (a PipelineDestinationInputsTable) FromSchema(schemaName string) *PipelineDestinationInputsTable {
	return newPipelineDestinationInputsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PipelineDestinationInputsTable with assigned table prefix
func (a PipelineDestinationInputsTable) WithPrefix(prefix string) *PipelineDestinationInputsTable {
	return newPipelineDestinationInputsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PipelineDestinationInputsTable with assigned table suffix
func (a PipelineDestinationInputsTable) WithSuffix(suffix string) *PipelineDestinationInputsTable {
	return newPipelineDestinationInputsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPipelineDestinationInputsTable(schemaName, tableName, alias string) *PipelineDestinationInputsTable {
	return &PipelineDestinationInputsTable{
		pipelineDestinationInputsTable: newPipelineDestinationInputsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                       newPipelineDestinationInputsTableImpl("", "excluded", ""),
	}
}

func newPipelineDestinationInputsTableImpl(schemaName, tableName, alias string) pipelineDestinationInputsTable {
	var (
		TenantIDColumn   = postgres.StringColumn("tenant_id")
		PipelineIDColumn = postgres.StringColumn("pipeline_id")
		TopicIDColumn    = postgres.StringColumn("topic_id")
		CreatedAtColumn  = postgres.TimestampColumn("created_at")
		UpdatedAtColumn  = postgres.TimestampColumn("updated_at")
		allColumns       = postgres.ColumnList{TenantIDColumn, PipelineIDColumn, TopicIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns   = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
		defaultColumns   = postgres.ColumnList{}
	)

	return pipelineDestinationInputsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:   TenantIDColumn,
		PipelineID: PipelineIDColumn,
		TopicID:    TopicIDColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
