//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PipelineTransformerInput = newPipelineTransformerInputTable("public", "pipeline_transformer_input", "")

type pipelineTransformerInputTable struct {
	postgres.Table

	// Columns
	TenantID      postgres.ColumnString
	PipelineID    postgres.ColumnString
	TransformerID postgres.ColumnString
	TopicID       postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PipelineTransformerInputTable struct {
	pipelineTransformerInputTable

	EXCLUDED pipelineTransformerInputTable
}

// AS creates new PipelineTransformerInputTable with assigned alias
func (a PipelineTransformerInputTable) AS(alias string) *PipelineTransformerInputTable {
	return newPipelineTransformerInputTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PipelineTransformerInputTable with assigned schema name
func (a PipelineTransformerInputTable) FromSchema(schemaName string) *PipelineTransformerInputTable {
	return newPipelineTransformerInputTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PipelineTransformerInputTable with assigned table prefix
func (a PipelineTransformerInputTable) WithPrefix(prefix string) *PipelineTransformerInputTable {
	return newPipelineTransformerInputTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PipelineTransformerInputTable with assigned table suffix
func (a PipelineTransformerInputTable) WithSuffix(suffix string) *PipelineTransformerInputTable {
	return newPipelineTransformerInputTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPipelineTransformerInputTable(schemaName, tableName, alias string) *PipelineTransformerInputTable {
	return &PipelineTransformerInputTable{
		pipelineTransformerInputTable: newPipelineTransformerInputTableImpl(schemaName, tableName, alias),
		EXCLUDED:                      newPipelineTransformerInputTableImpl("", "excluded", ""),
	}
}

func newPipelineTransformerInputTableImpl(schemaName, tableName, alias string) pipelineTransformerInputTable {
	var (
		TenantIDColumn      = postgres.StringColumn("tenant_id")
		PipelineIDColumn    = postgres.StringColumn("pipeline_id")
		TransformerIDColumn = postgres.StringColumn("transformer_id")
		TopicIDColumn       = postgres.StringColumn("topic_id")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{TenantIDColumn, PipelineIDColumn, TransformerIDColumn, TopicIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{}
	)

	return pipelineTransformerInputTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:      TenantIDColumn,
		PipelineID:    PipelineIDColumn,
		TransformerID: TransformerIDColumn,
		TopicID:       TopicIDColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
