//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PipelineDestinationInput = newPipelineDestinationInputTable("public", "pipeline_destination_input", "")

type pipelineDestinationInputTable struct {
	postgres.Table

	// Columns
	TenantID   postgres.ColumnString
	PipelineID postgres.ColumnString
	TopicID    postgres.ColumnString
	CreatedAt  postgres.ColumnTimestamp
	UpdatedAt  postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PipelineDestinationInputTable struct {
	pipelineDestinationInputTable

	EXCLUDED pipelineDestinationInputTable
}

// AS creates new PipelineDestinationInputTable with assigned alias
func (a PipelineDestinationInputTable) AS(alias string) *PipelineDestinationInputTable {
	return newPipelineDestinationInputTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PipelineDestinationInputTable with assigned schema name
func (a PipelineDestinationInputTable) FromSchema(schemaName string) *PipelineDestinationInputTable {
	return newPipelineDestinationInputTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PipelineDestinationInputTable with assigned table prefix
func (a PipelineDestinationInputTable) WithPrefix(prefix string) *PipelineDestinationInputTable {
	return newPipelineDestinationInputTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PipelineDestinationInputTable with assigned table suffix
func (a PipelineDestinationInputTable) WithSuffix(suffix string) *PipelineDestinationInputTable {
	return newPipelineDestinationInputTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPipelineDestinationInputTable(schemaName, tableName, alias string) *PipelineDestinationInputTable {
	return &PipelineDestinationInputTable{
		pipelineDestinationInputTable: newPipelineDestinationInputTableImpl(schemaName, tableName, alias),
		EXCLUDED:                      newPipelineDestinationInputTableImpl("", "excluded", ""),
	}
}

func newPipelineDestinationInputTableImpl(schemaName, tableName, alias string) pipelineDestinationInputTable {
	var (
		TenantIDColumn   = postgres.StringColumn("tenant_id")
		PipelineIDColumn = postgres.StringColumn("pipeline_id")
		TopicIDColumn    = postgres.StringColumn("topic_id")
		CreatedAtColumn  = postgres.TimestampColumn("created_at")
		UpdatedAtColumn  = postgres.TimestampColumn("updated_at")
		allColumns       = postgres.ColumnList{TenantIDColumn, PipelineIDColumn, TopicIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns   = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
		defaultColumns   = postgres.ColumnList{}
	)

	return pipelineDestinationInputTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:   TenantIDColumn,
		PipelineID: PipelineIDColumn,
		TopicID:    TopicIDColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
