//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Pipelines = newPipelinesTable("public", "pipelines", "")

type pipelinesTable struct {
	postgres.Table

	// Columns
	TenantID        postgres.ColumnString
	PipelineID      postgres.ColumnString
	Name            postgres.ColumnString
	SourceID        postgres.ColumnString
	DestinationID   postgres.ColumnString
	Config          postgres.ColumnString
	CreatedByUserID postgres.ColumnString
	UpdatedByUserID postgres.ColumnString
	CreatedAt       postgres.ColumnTimestamp
	UpdatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PipelinesTable struct {
	pipelinesTable

	EXCLUDED pipelinesTable
}

// AS creates new PipelinesTable with assigned alias
func (a PipelinesTable) AS(alias string) *PipelinesTable {
	return newPipelinesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PipelinesTable with assigned schema name
func (a PipelinesTable) FromSchema(schemaName string) *PipelinesTable {
	return newPipelinesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PipelinesTable with assigned table prefix
func (a PipelinesTable) WithPrefix(prefix string) *PipelinesTable {
	return newPipelinesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PipelinesTable with assigned table suffix
func (a PipelinesTable) WithSuffix(suffix string) *PipelinesTable {
	return newPipelinesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPipelinesTable(schemaName, tableName, alias string) *PipelinesTable {
	return &PipelinesTable{
		pipelinesTable: newPipelinesTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newPipelinesTableImpl("", "excluded", ""),
	}
}

func newPipelinesTableImpl(schemaName, tableName, alias string) pipelinesTable {
	var (
		TenantIDColumn        = postgres.StringColumn("tenant_id")
		PipelineIDColumn      = postgres.StringColumn("pipeline_id")
		NameColumn            = postgres.StringColumn("name")
		SourceIDColumn        = postgres.StringColumn("source_id")
		DestinationIDColumn   = postgres.StringColumn("destination_id")
		ConfigColumn          = postgres.StringColumn("config")
		CreatedByUserIDColumn = postgres.StringColumn("created_by_user_id")
		UpdatedByUserIDColumn = postgres.StringColumn("updated_by_user_id")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		allColumns            = postgres.ColumnList{TenantIDColumn, PipelineIDColumn, NameColumn, SourceIDColumn, DestinationIDColumn, ConfigColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, SourceIDColumn, DestinationIDColumn, ConfigColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns        = postgres.ColumnList{}
	)

	return pipelinesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:        TenantIDColumn,
		PipelineID:      PipelineIDColumn,
		Name:            NameColumn,
		SourceID:        SourceIDColumn,
		DestinationID:   DestinationIDColumn,
		Config:          ConfigColumn,
		CreatedByUserID: CreatedByUserIDColumn,
		UpdatedByUserID: UpdatedByUserIDColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
