//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PipelineTransformers = newPipelineTransformersTable("public", "pipeline_transformers", "")

type pipelineTransformersTable struct {
	postgres.Table

	// Columns
	TenantID      postgres.ColumnString
	PipelineID    postgres.ColumnString
	TransformerID postgres.ColumnString
	Stage         postgres.ColumnInteger
	Config        postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PipelineTransformersTable struct {
	pipelineTransformersTable

	EXCLUDED pipelineTransformersTable
}

// AS creates new PipelineTransformersTable with assigned alias
func (a PipelineTransformersTable) AS(alias string) *PipelineTransformersTable {
	return newPipelineTransformersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PipelineTransformersTable with assigned schema name
func (a PipelineTransformersTable) FromSchema(schemaName string) *PipelineTransformersTable {
	return newPipelineTransformersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PipelineTransformersTable with assigned table prefix
func (a PipelineTransformersTable) WithPrefix(prefix string) *PipelineTransformersTable {
	return newPipelineTransformersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PipelineTransformersTable with assigned table suffix
func (a PipelineTransformersTable) WithSuffix(suffix string) *PipelineTransformersTable {
	return newPipelineTransformersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPipelineTransformersTable(schemaName, tableName, alias string) *PipelineTransformersTable {
	return &PipelineTransformersTable{
		pipelineTransformersTable: newPipelineTransformersTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newPipelineTransformersTableImpl("", "excluded", ""),
	}
}

func newPipelineTransformersTableImpl(schemaName, tableName, alias string) pipelineTransformersTable {
	var (
		TenantIDColumn      = postgres.StringColumn("tenant_id")
		PipelineIDColumn    = postgres.StringColumn("pipeline_id")
		TransformerIDColumn = postgres.StringColumn("transformer_id")
		StageColumn         = postgres.IntegerColumn("stage")
		ConfigColumn        = postgres.StringColumn("config")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{TenantIDColumn, PipelineIDColumn, TransformerIDColumn, StageColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{StageColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{}
	)

	return pipelineTransformersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:      TenantIDColumn,
		PipelineID:    PipelineIDColumn,
		TransformerID: TransformerIDColumn,
		Stage:         StageColumn,
		Config:        ConfigColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
