//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Source = newSourceTable("public", "source", "")

type sourceTable struct {
	postgres.Table

	// Columns
	TenantID        postgres.ColumnString
	SourceID        postgres.ColumnString
	Name            postgres.ColumnString
	Engine          postgres.ColumnString
	Config          postgres.ColumnString
	CreatedByUserID postgres.ColumnString
	UpdatedByUserID postgres.ColumnString
	CreatedAt       postgres.ColumnTimestamp
	UpdatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SourceTable struct {
	sourceTable

	EXCLUDED sourceTable
}

// AS creates new SourceTable with assigned alias
func (a SourceTable) AS(alias string) *SourceTable {
	return newSourceTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SourceTable with assigned schema name
func (a SourceTable) FromSchema(schemaName string) *SourceTable {
	return newSourceTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SourceTable with assigned table prefix
func (a SourceTable) WithPrefix(prefix string) *SourceTable {
	return newSourceTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SourceTable with assigned table suffix
func (a SourceTable) WithSuffix(suffix string) *SourceTable {
	return newSourceTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSourceTable(schemaName, tableName, alias string) *SourceTable {
	return &SourceTable{
		sourceTable: newSourceTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newSourceTableImpl("", "excluded", ""),
	}
}

func newSourceTableImpl(schemaName, tableName, alias string) sourceTable {
	var (
		TenantIDColumn        = postgres.StringColumn("tenant_id")
		SourceIDColumn        = postgres.StringColumn("source_id")
		NameColumn            = postgres.StringColumn("name")
		EngineColumn          = postgres.StringColumn("engine")
		ConfigColumn          = postgres.StringColumn("config")
		CreatedByUserIDColumn = postgres.StringColumn("created_by_user_id")
		UpdatedByUserIDColumn = postgres.StringColumn("updated_by_user_id")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		allColumns            = postgres.ColumnList{TenantIDColumn, SourceIDColumn, NameColumn, EngineColumn, ConfigColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, EngineColumn, ConfigColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns        = postgres.ColumnList{}
	)

	return sourceTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:        TenantIDColumn,
		SourceID:        SourceIDColumn,
		Name:            NameColumn,
		Engine:          EngineColumn,
		Config:          ConfigColumn,
		CreatedByUserID: CreatedByUserIDColumn,
		UpdatedByUserID: UpdatedByUserIDColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
