//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SourceOutputs = newSourceOutputsTable("public", "source_outputs", "")

type sourceOutputsTable struct {
	postgres.Table

	// Columns
	TenantID       postgres.ColumnString
	SourceID       postgres.ColumnString
	TopicID        postgres.ColumnString
	DatabaseName   postgres.ColumnString
	GroupName      postgres.ColumnString
	CollectionName postgres.ColumnString
	Config         postgres.ColumnString
	CreatedAt      postgres.ColumnTimestamp
	UpdatedAt      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SourceOutputsTable struct {
	sourceOutputsTable

	EXCLUDED sourceOutputsTable
}

// AS creates new SourceOutputsTable with assigned alias
func (a SourceOutputsTable) AS(alias string) *SourceOutputsTable {
	return newSourceOutputsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SourceOutputsTable with assigned schema name
func (a SourceOutputsTable) FromSchema(schemaName string) *SourceOutputsTable {
	return newSourceOutputsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SourceOutputsTable with assigned table prefix
func (a SourceOutputsTable) WithPrefix(prefix string) *SourceOutputsTable {
	return newSourceOutputsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SourceOutputsTable with assigned table suffix
func (a SourceOutputsTable) WithSuffix(suffix string) *SourceOutputsTable {
	return newSourceOutputsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSourceOutputsTable(schemaName, tableName, alias string) *SourceOutputsTable {
	return &SourceOutputsTable{
		sourceOutputsTable: newSourceOutputsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newSourceOutputsTableImpl("", "excluded", ""),
	}
}

func newSourceOutputsTableImpl(schemaName, tableName, alias string) sourceOutputsTable {
	var (
		TenantIDColumn       = postgres.StringColumn("tenant_id")
		SourceIDColumn       = postgres.StringColumn("source_id")
		TopicIDColumn        = postgres.StringColumn("topic_id")
		DatabaseNameColumn   = postgres.StringColumn("database_name")
		GroupNameColumn      = postgres.StringColumn("group_name")
		CollectionNameColumn = postgres.StringColumn("collection_name")
		ConfigColumn         = postgres.StringColumn("config")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampColumn("updated_at")
		allColumns           = postgres.ColumnList{TenantIDColumn, SourceIDColumn, TopicIDColumn, DatabaseNameColumn, GroupNameColumn, CollectionNameColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns       = postgres.ColumnList{DatabaseNameColumn, GroupNameColumn, CollectionNameColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns       = postgres.ColumnList{}
	)

	return sourceOutputsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:       TenantIDColumn,
		SourceID:       SourceIDColumn,
		TopicID:        TopicIDColumn,
		DatabaseName:   DatabaseNameColumn,
		GroupName:      GroupNameColumn,
		CollectionName: CollectionNameColumn,
		Config:         ConfigColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
