//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SourceOutput = newSourceOutputTable("public", "source_output", "")

type sourceOutputTable struct {
	postgres.Table

	// Columns
	TenantID       postgres.ColumnString
	SourceID       postgres.ColumnString
	TopicID        postgres.ColumnString
	DatabaseName   postgres.ColumnString
	GroupName      postgres.ColumnString
	CollectionName postgres.ColumnString
	Config         postgres.ColumnString
	CreatedAt      postgres.ColumnTimestamp
	UpdatedAt      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SourceOutputTable struct {
	sourceOutputTable

	EXCLUDED sourceOutputTable
}

// AS creates new SourceOutputTable with assigned alias
func (a SourceOutputTable) AS(alias string) *SourceOutputTable {
	return newSourceOutputTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SourceOutputTable with assigned schema name
func (a SourceOutputTable) FromSchema(schemaName string) *SourceOutputTable {
	return newSourceOutputTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SourceOutputTable with assigned table prefix
func (a SourceOutputTable) WithPrefix(prefix string) *SourceOutputTable {
	return newSourceOutputTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SourceOutputTable with assigned table suffix
func (a SourceOutputTable) WithSuffix(suffix string) *SourceOutputTable {
	return newSourceOutputTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSourceOutputTable(schemaName, tableName, alias string) *SourceOutputTable {
	return &SourceOutputTable{
		sourceOutputTable: newSourceOutputTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newSourceOutputTableImpl("", "excluded", ""),
	}
}

func newSourceOutputTableImpl(schemaName, tableName, alias string) sourceOutputTable {
	var (
		TenantIDColumn       = postgres.StringColumn("tenant_id")
		SourceIDColumn       = postgres.StringColumn("source_id")
		TopicIDColumn        = postgres.StringColumn("topic_id")
		DatabaseNameColumn   = postgres.StringColumn("database_name")
		GroupNameColumn      = postgres.StringColumn("group_name")
		CollectionNameColumn = postgres.StringColumn("collection_name")
		ConfigColumn         = postgres.StringColumn("config")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampColumn("updated_at")
		allColumns           = postgres.ColumnList{TenantIDColumn, SourceIDColumn, TopicIDColumn, DatabaseNameColumn, GroupNameColumn, CollectionNameColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns       = postgres.ColumnList{DatabaseNameColumn, GroupNameColumn, CollectionNameColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns       = postgres.ColumnList{}
	)

	return sourceOutputTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:       TenantIDColumn,
		SourceID:       SourceIDColumn,
		TopicID:        TopicIDColumn,
		DatabaseName:   DatabaseNameColumn,
		GroupName:      GroupNameColumn,
		CollectionName: CollectionNameColumn,
		Config:         ConfigColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
