//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Sources = newSourcesTable("public", "sources", "")

type sourcesTable struct {
	postgres.Table

	// Columns
	TenantID        postgres.ColumnString
	SourceID        postgres.ColumnString
	Name            postgres.ColumnString
	Engine          postgres.ColumnString
	Config          postgres.ColumnString
	CreatedByUserID postgres.ColumnString
	UpdatedByUserID postgres.ColumnString
	CreatedAt       postgres.ColumnTimestamp
	UpdatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SourcesTable struct {
	sourcesTable

	EXCLUDED sourcesTable
}

// AS creates new SourcesTable with assigned alias
func (a SourcesTable) AS(alias string) *SourcesTable {
	return newSourcesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SourcesTable with assigned schema name
func (a SourcesTable) FromSchema(schemaName string) *SourcesTable {
	return newSourcesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SourcesTable with assigned table prefix
func (a SourcesTable) WithPrefix(prefix string) *SourcesTable {
	return newSourcesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SourcesTable with assigned table suffix
func (a SourcesTable) WithSuffix(suffix string) *SourcesTable {
	return newSourcesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSourcesTable(schemaName, tableName, alias string) *SourcesTable {
	return &SourcesTable{
		sourcesTable: newSourcesTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newSourcesTableImpl("", "excluded", ""),
	}
}

func newSourcesTableImpl(schemaName, tableName, alias string) sourcesTable {
	var (
		TenantIDColumn        = postgres.StringColumn("tenant_id")
		SourceIDColumn        = postgres.StringColumn("source_id")
		NameColumn            = postgres.StringColumn("name")
		EngineColumn          = postgres.StringColumn("engine")
		ConfigColumn          = postgres.StringColumn("config")
		CreatedByUserIDColumn = postgres.StringColumn("created_by_user_id")
		UpdatedByUserIDColumn = postgres.StringColumn("updated_by_user_id")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		allColumns            = postgres.ColumnList{TenantIDColumn, SourceIDColumn, NameColumn, EngineColumn, ConfigColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, EngineColumn, ConfigColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns        = postgres.ColumnList{}
	)

	return sourcesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:        TenantIDColumn,
		SourceID:        SourceIDColumn,
		Name:            NameColumn,
		Engine:          EngineColumn,
		Config:          ConfigColumn,
		CreatedByUserID: CreatedByUserIDColumn,
		UpdatedByUserID: UpdatedByUserIDColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
