//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Destinations = Destinations.FromSchema(schema)
	PipelineDestinationInputs = PipelineDestinationInputs.FromSchema(schema)
	PipelineTransformerInputs = PipelineTransformerInputs.FromSchema(schema)
	PipelineTransformers = PipelineTransformers.FromSchema(schema)
	Pipelines = Pipelines.FromSchema(schema)
	SourceOutputs = SourceOutputs.FromSchema(schema)
	Sources = Sources.FromSchema(schema)
	Tags = Tags.FromSchema(schema)
	TenantInfras = TenantInfras.FromSchema(schema)
	TenantUsers = TenantUsers.FromSchema(schema)
	Tenants = Tenants.FromSchema(schema)
	Topics = Topics.FromSchema(schema)
	TransformerInputs = TransformerInputs.FromSchema(schema)
	TransformerOutputs = TransformerOutputs.FromSchema(schema)
	Transformers = Transformers.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
