//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Destination = Destination.FromSchema(schema)
	Pipeline = Pipeline.FromSchema(schema)
	PipelineDestinationInput = PipelineDestinationInput.FromSchema(schema)
	PipelineTransformer = PipelineTransformer.FromSchema(schema)
	PipelineTransformerInput = PipelineTransformerInput.FromSchema(schema)
	Source = Source.FromSchema(schema)
	SourceOutput = SourceOutput.FromSchema(schema)
	Tag = Tag.FromSchema(schema)
	Tenant = Tenant.FromSchema(schema)
	TenantInfra = TenantInfra.FromSchema(schema)
	TenantUser = TenantUser.FromSchema(schema)
	Topic = Topic.FromSchema(schema)
	Transformer = Transformer.FromSchema(schema)
	TransformerInput = TransformerInput.FromSchema(schema)
	TransformerOutput = TransformerOutput.FromSchema(schema)
	User = User.FromSchema(schema)
}
