//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Tags = newTagsTable("public", "tags", "")

type tagsTable struct {
	postgres.Table

	// Columns
	TenantID        postgres.ColumnString
	TagID           postgres.ColumnString
	Key             postgres.ColumnString
	Value           postgres.ColumnString
	CreatedByUserID postgres.ColumnString
	UpdatedByUserID postgres.ColumnString
	CreatedAt       postgres.ColumnTimestamp
	UpdatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TagsTable struct {
	tagsTable

	EXCLUDED tagsTable
}

// AS creates new TagsTable with assigned alias
func (a TagsTable) AS(alias string) *TagsTable {
	return newTagsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TagsTable with assigned schema name
func (a TagsTable) FromSchema(schemaName string) *TagsTable {
	return newTagsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TagsTable with assigned table prefix
func (a TagsTable) WithPrefix(prefix string) *TagsTable {
	return newTagsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TagsTable with assigned table suffix
func (a TagsTable) WithSuffix(suffix string) *TagsTable {
	return newTagsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTagsTable(schemaName, tableName, alias string) *TagsTable {
	return &TagsTable{
		tagsTable: newTagsTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newTagsTableImpl("", "excluded", ""),
	}
}

func newTagsTableImpl(schemaName, tableName, alias string) tagsTable {
	var (
		TenantIDColumn        = postgres.StringColumn("tenant_id")
		TagIDColumn           = postgres.StringColumn("tag_id")
		KeyColumn             = postgres.StringColumn("key")
		ValueColumn           = postgres.StringColumn("value")
		CreatedByUserIDColumn = postgres.StringColumn("created_by_user_id")
		UpdatedByUserIDColumn = postgres.StringColumn("updated_by_user_id")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		allColumns            = postgres.ColumnList{TenantIDColumn, TagIDColumn, KeyColumn, ValueColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{KeyColumn, ValueColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns        = postgres.ColumnList{}
	)

	return tagsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:        TenantIDColumn,
		TagID:           TagIDColumn,
		Key:             KeyColumn,
		Value:           ValueColumn,
		CreatedByUserID: CreatedByUserIDColumn,
		UpdatedByUserID: UpdatedByUserIDColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
