//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TenantUser = newTenantUserTable("public", "tenant_user", "")

type tenantUserTable struct {
	postgres.Table

	// Columns
	TenantID  postgres.ColumnString
	UserID    postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TenantUserTable struct {
	tenantUserTable

	EXCLUDED tenantUserTable
}

// AS creates new TenantUserTable with assigned alias
func (a TenantUserTable) AS(alias string) *TenantUserTable {
	return newTenantUserTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TenantUserTable with assigned schema name
func (a TenantUserTable) FromSchema(schemaName string) *TenantUserTable {
	return newTenantUserTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TenantUserTable with assigned table prefix
func (a TenantUserTable) WithPrefix(prefix string) *TenantUserTable {
	return newTenantUserTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TenantUserTable with assigned table suffix
func (a TenantUserTable) WithSuffix(suffix string) *TenantUserTable {
	return newTenantUserTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTenantUserTable(schemaName, tableName, alias string) *TenantUserTable {
	return &TenantUserTable{
		tenantUserTable: newTenantUserTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newTenantUserTableImpl("", "excluded", ""),
	}
}

func newTenantUserTableImpl(schemaName, tableName, alias string) tenantUserTable {
	var (
		TenantIDColumn  = postgres.StringColumn("tenant_id")
		UserIDColumn    = postgres.StringColumn("user_id")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{TenantIDColumn, UserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return tenantUserTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:  TenantIDColumn,
		UserID:    UserIDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
