//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TenantUsers = newTenantUsersTable("public", "tenant_users", "")

type tenantUsersTable struct {
	postgres.Table

	// Columns
	TenantID  postgres.ColumnString
	UserID    postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TenantUsersTable struct {
	tenantUsersTable

	EXCLUDED tenantUsersTable
}

// AS creates new TenantUsersTable with assigned alias
func (a TenantUsersTable) AS(alias string) *TenantUsersTable {
	return newTenantUsersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TenantUsersTable with assigned schema name
func (a TenantUsersTable) FromSchema(schemaName string) *TenantUsersTable {
	return newTenantUsersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TenantUsersTable with assigned table prefix
func (a TenantUsersTable) WithPrefix(prefix string) *TenantUsersTable {
	return newTenantUsersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TenantUsersTable with assigned table suffix
func (a TenantUsersTable) WithSuffix(suffix string) *TenantUsersTable {
	return newTenantUsersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTenantUsersTable(schemaName, tableName, alias string) *TenantUsersTable {
	return &TenantUsersTable{
		tenantUsersTable: newTenantUsersTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newTenantUsersTableImpl("", "excluded", ""),
	}
}

func newTenantUsersTableImpl(schemaName, tableName, alias string) tenantUsersTable {
	var (
		TenantIDColumn  = postgres.StringColumn("tenant_id")
		UserIDColumn    = postgres.StringColumn("user_id")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{TenantIDColumn, UserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return tenantUsersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:  TenantIDColumn,
		UserID:    UserIDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
