//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TenantInfra = newTenantInfraTable("public", "tenant_infra", "")

type tenantInfraTable struct {
	postgres.Table

	// Columns
	TenantInfraID     postgres.ColumnString
	Name              postgres.ColumnString
	KafkaBrokers      postgres.ColumnString
	SchemaRegistryURL postgres.ColumnString
	KafkaConnectURL   postgres.ColumnString
	KmsKey            postgres.ColumnString
	CreatedAt         postgres.ColumnTimestamp
	UpdatedAt         postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TenantInfraTable struct {
	tenantInfraTable

	EXCLUDED tenantInfraTable
}

// AS creates new TenantInfraTable with assigned alias
func (a TenantInfraTable) AS(alias string) *TenantInfraTable {
	return newTenantInfraTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TenantInfraTable with assigned schema name
func (a TenantInfraTable) FromSchema(schemaName string) *TenantInfraTable {
	return newTenantInfraTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TenantInfraTable with assigned table prefix
func (a TenantInfraTable) WithPrefix(prefix string) *TenantInfraTable {
	return newTenantInfraTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TenantInfraTable with assigned table suffix
func (a TenantInfraTable) WithSuffix(suffix string) *TenantInfraTable {
	return newTenantInfraTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTenantInfraTable(schemaName, tableName, alias string) *TenantInfraTable {
	return &TenantInfraTable{
		tenantInfraTable: newTenantInfraTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newTenantInfraTableImpl("", "excluded", ""),
	}
}

func newTenantInfraTableImpl(schemaName, tableName, alias string) tenantInfraTable {
	var (
		TenantInfraIDColumn     = postgres.StringColumn("tenant_infra_id")
		NameColumn              = postgres.StringColumn("name")
		KafkaBrokersColumn      = postgres.StringColumn("kafka_brokers")
		SchemaRegistryURLColumn = postgres.StringColumn("schema_registry_url")
		KafkaConnectURLColumn   = postgres.StringColumn("kafka_connect_url")
		KmsKeyColumn            = postgres.StringColumn("kms_key")
		CreatedAtColumn         = postgres.TimestampColumn("created_at")
		UpdatedAtColumn         = postgres.TimestampColumn("updated_at")
		allColumns              = postgres.ColumnList{TenantInfraIDColumn, NameColumn, KafkaBrokersColumn, SchemaRegistryURLColumn, KafkaConnectURLColumn, KmsKeyColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns          = postgres.ColumnList{NameColumn, KafkaBrokersColumn, SchemaRegistryURLColumn, KafkaConnectURLColumn, KmsKeyColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns          = postgres.ColumnList{}
	)

	return tenantInfraTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantInfraID:     TenantInfraIDColumn,
		Name:              NameColumn,
		KafkaBrokers:      KafkaBrokersColumn,
		SchemaRegistryURL: SchemaRegistryURLColumn,
		KafkaConnectURL:   KafkaConnectURLColumn,
		KmsKey:            KmsKeyColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
