//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TenantInfras = newTenantInfrasTable("public", "tenant_infras", "")

type tenantInfrasTable struct {
	postgres.Table

	// Columns
	TenantInfraID     postgres.ColumnString
	Name              postgres.ColumnString
	KafkaBrokers      postgres.ColumnString
	SchemaRegistryURL postgres.ColumnString
	KafkaConnectURL   postgres.ColumnString
	KmsKey            postgres.ColumnString
	CreatedAt         postgres.ColumnTimestamp
	UpdatedAt         postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TenantInfrasTable struct {
	tenantInfrasTable

	EXCLUDED tenantInfrasTable
}

// AS creates new TenantInfrasTable with assigned alias
func (a TenantInfrasTable) AS(alias string) *TenantInfrasTable {
	return newTenantInfrasTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TenantInfrasTable with assigned schema name
func (a TenantInfrasTable) FromSchema(schemaName string) *TenantInfrasTable {
	return newTenantInfrasTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TenantInfrasTable with assigned table prefix
func (a TenantInfrasTable) WithPrefix(prefix string) *TenantInfrasTable {
	return newTenantInfrasTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TenantInfrasTable with assigned table suffix
func (a TenantInfrasTable) WithSuffix(suffix string) *TenantInfrasTable {
	return newTenantInfrasTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTenantInfrasTable(schemaName, tableName, alias string) *TenantInfrasTable {
	return &TenantInfrasTable{
		tenantInfrasTable: newTenantInfrasTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newTenantInfrasTableImpl("", "excluded", ""),
	}
}

func newTenantInfrasTableImpl(schemaName, tableName, alias string) tenantInfrasTable {
	var (
		TenantInfraIDColumn     = postgres.StringColumn("tenant_infra_id")
		NameColumn              = postgres.StringColumn("name")
		KafkaBrokersColumn      = postgres.StringColumn("kafka_brokers")
		SchemaRegistryURLColumn = postgres.StringColumn("schema_registry_url")
		KafkaConnectURLColumn   = postgres.StringColumn("kafka_connect_url")
		KmsKeyColumn            = postgres.StringColumn("kms_key")
		CreatedAtColumn         = postgres.TimestampColumn("created_at")
		UpdatedAtColumn         = postgres.TimestampColumn("updated_at")
		allColumns              = postgres.ColumnList{TenantInfraIDColumn, NameColumn, KafkaBrokersColumn, SchemaRegistryURLColumn, KafkaConnectURLColumn, KmsKeyColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns          = postgres.ColumnList{NameColumn, KafkaBrokersColumn, SchemaRegistryURLColumn, KafkaConnectURLColumn, KmsKeyColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns          = postgres.ColumnList{}
	)

	return tenantInfrasTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantInfraID:     TenantInfraIDColumn,
		Name:              NameColumn,
		KafkaBrokers:      KafkaBrokersColumn,
		SchemaRegistryURL: SchemaRegistryURLColumn,
		KafkaConnectURL:   KafkaConnectURLColumn,
		KmsKey:            KmsKeyColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
