//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Tenants = newTenantsTable("public", "tenants", "")

type tenantsTable struct {
	postgres.Table

	// Columns
	TenantID  postgres.ColumnString
	Name      postgres.ColumnString
	Domain    postgres.ColumnString
	Tier      postgres.ColumnString
	InfraID   postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TenantsTable struct {
	tenantsTable

	EXCLUDED tenantsTable
}

// AS creates new TenantsTable with assigned alias
func (a TenantsTable) AS(alias string) *TenantsTable {
	return newTenantsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TenantsTable with assigned schema name
func (a TenantsTable) FromSchema(schemaName string) *TenantsTable {
	return newTenantsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TenantsTable with assigned table prefix
func (a TenantsTable) WithPrefix(prefix string) *TenantsTable {
	return newTenantsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TenantsTable with assigned table suffix
func (a TenantsTable) WithSuffix(suffix string) *TenantsTable {
	return newTenantsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTenantsTable(schemaName, tableName, alias string) *TenantsTable {
	return &TenantsTable{
		tenantsTable: newTenantsTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newTenantsTableImpl("", "excluded", ""),
	}
}

func newTenantsTableImpl(schemaName, tableName, alias string) tenantsTable {
	var (
		TenantIDColumn  = postgres.StringColumn("tenant_id")
		NameColumn      = postgres.StringColumn("name")
		DomainColumn    = postgres.StringColumn("domain")
		TierColumn      = postgres.StringColumn("tier")
		InfraIDColumn   = postgres.StringColumn("infra_id")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{TenantIDColumn, NameColumn, DomainColumn, TierColumn, InfraIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{NameColumn, DomainColumn, TierColumn, InfraIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return tenantsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:  TenantIDColumn,
		Name:      NameColumn,
		Domain:    DomainColumn,
		Tier:      TierColumn,
		InfraID:   InfraIDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
