//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Tenant = newTenantTable("public", "tenant", "")

type tenantTable struct {
	postgres.Table

	// Columns
	TenantID  postgres.ColumnString
	Name      postgres.ColumnString
	Domain    postgres.ColumnString
	Tier      postgres.ColumnString
	InfraID   postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TenantTable struct {
	tenantTable

	EXCLUDED tenantTable
}

// AS creates new TenantTable with assigned alias
func (a TenantTable) AS(alias string) *TenantTable {
	return newTenantTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TenantTable with assigned schema name
func (a TenantTable) FromSchema(schemaName string) *TenantTable {
	return newTenantTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TenantTable with assigned table prefix
func (a TenantTable) WithPrefix(prefix string) *TenantTable {
	return newTenantTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TenantTable with assigned table suffix
func (a TenantTable) WithSuffix(suffix string) *TenantTable {
	return newTenantTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTenantTable(schemaName, tableName, alias string) *TenantTable {
	return &TenantTable{
		tenantTable: newTenantTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newTenantTableImpl("", "excluded", ""),
	}
}

func newTenantTableImpl(schemaName, tableName, alias string) tenantTable {
	var (
		TenantIDColumn  = postgres.StringColumn("tenant_id")
		NameColumn      = postgres.StringColumn("name")
		DomainColumn    = postgres.StringColumn("domain")
		TierColumn      = postgres.StringColumn("tier")
		InfraIDColumn   = postgres.StringColumn("infra_id")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{TenantIDColumn, NameColumn, DomainColumn, TierColumn, InfraIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{NameColumn, DomainColumn, TierColumn, InfraIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return tenantTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:  TenantIDColumn,
		Name:      NameColumn,
		Domain:    DomainColumn,
		Tier:      TierColumn,
		InfraID:   InfraIDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
