//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Topics = newTopicsTable("public", "topics", "")

type topicsTable struct {
	postgres.Table

	// Columns
	TenantID     postgres.ColumnString
	TopicID      postgres.ColumnString
	Name         postgres.ColumnString
	ProducerType postgres.ColumnString
	ProducerID   postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	UpdatedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TopicsTable struct {
	topicsTable

	EXCLUDED topicsTable
}

// AS creates new TopicsTable with assigned alias
func (a TopicsTable) AS(alias string) *TopicsTable {
	return newTopicsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TopicsTable with assigned schema name
func (a TopicsTable) FromSchema(schemaName string) *TopicsTable {
	return newTopicsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TopicsTable with assigned table prefix
func (a TopicsTable) WithPrefix(prefix string) *TopicsTable {
	return newTopicsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TopicsTable with assigned table suffix
func (a TopicsTable) WithSuffix(suffix string) *TopicsTable {
	return newTopicsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTopicsTable(schemaName, tableName, alias string) *TopicsTable {
	return &TopicsTable{
		topicsTable: newTopicsTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newTopicsTableImpl("", "excluded", ""),
	}
}

func newTopicsTableImpl(schemaName, tableName, alias string) topicsTable {
	var (
		TenantIDColumn     = postgres.StringColumn("tenant_id")
		TopicIDColumn      = postgres.StringColumn("topic_id")
		NameColumn         = postgres.StringColumn("name")
		ProducerTypeColumn = postgres.StringColumn("producer_type")
		ProducerIDColumn   = postgres.StringColumn("producer_id")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		allColumns         = postgres.ColumnList{TenantIDColumn, TopicIDColumn, NameColumn, ProducerTypeColumn, ProducerIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{NameColumn, ProducerTypeColumn, ProducerIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns     = postgres.ColumnList{}
	)

	return topicsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:     TenantIDColumn,
		TopicID:      TopicIDColumn,
		Name:         NameColumn,
		ProducerType: ProducerTypeColumn,
		ProducerID:   ProducerIDColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
