//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Topic = newTopicTable("public", "topic", "")

type topicTable struct {
	postgres.Table

	// Columns
	TenantID     postgres.ColumnString
	TopicID      postgres.ColumnString
	Name         postgres.ColumnString
	ProducerType postgres.ColumnString
	ProducerID   postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	UpdatedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TopicTable struct {
	topicTable

	EXCLUDED topicTable
}

// AS creates new TopicTable with assigned alias
func (a TopicTable) AS(alias string) *TopicTable {
	return newTopicTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TopicTable with assigned schema name
func (a TopicTable) FromSchema(schemaName string) *TopicTable {
	return newTopicTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TopicTable with assigned table prefix
func (a TopicTable) WithPrefix(prefix string) *TopicTable {
	return newTopicTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TopicTable with assigned table suffix
func (a TopicTable) WithSuffix(suffix string) *TopicTable {
	return newTopicTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTopicTable(schemaName, tableName, alias string) *TopicTable {
	return &TopicTable{
		topicTable: newTopicTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newTopicTableImpl("", "excluded", ""),
	}
}

func newTopicTableImpl(schemaName, tableName, alias string) topicTable {
	var (
		TenantIDColumn     = postgres.StringColumn("tenant_id")
		TopicIDColumn      = postgres.StringColumn("topic_id")
		NameColumn         = postgres.StringColumn("name")
		ProducerTypeColumn = postgres.StringColumn("producer_type")
		ProducerIDColumn   = postgres.StringColumn("producer_id")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		allColumns         = postgres.ColumnList{TenantIDColumn, TopicIDColumn, NameColumn, ProducerTypeColumn, ProducerIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{NameColumn, ProducerTypeColumn, ProducerIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns     = postgres.ColumnList{}
	)

	return topicTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:     TenantIDColumn,
		TopicID:      TopicIDColumn,
		Name:         NameColumn,
		ProducerType: ProducerTypeColumn,
		ProducerID:   ProducerIDColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
