//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Transformers = newTransformersTable("public", "transformers", "")

type transformersTable struct {
	postgres.Table

	// Columns
	TenantID        postgres.ColumnString
	TransfomerID    postgres.ColumnString
	Name            postgres.ColumnString
	Config          postgres.ColumnString
	CreatedByUserID postgres.ColumnString
	UpdatedByUserID postgres.ColumnString
	CreatedAt       postgres.ColumnTimestamp
	UpdatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TransformersTable struct {
	transformersTable

	EXCLUDED transformersTable
}

// AS creates new TransformersTable with assigned alias
func (a TransformersTable) AS(alias string) *TransformersTable {
	return newTransformersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TransformersTable with assigned schema name
func (a TransformersTable) FromSchema(schemaName string) *TransformersTable {
	return newTransformersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TransformersTable with assigned table prefix
func (a TransformersTable) WithPrefix(prefix string) *TransformersTable {
	return newTransformersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TransformersTable with assigned table suffix
func (a TransformersTable) WithSuffix(suffix string) *TransformersTable {
	return newTransformersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTransformersTable(schemaName, tableName, alias string) *TransformersTable {
	return &TransformersTable{
		transformersTable: newTransformersTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newTransformersTableImpl("", "excluded", ""),
	}
}

func newTransformersTableImpl(schemaName, tableName, alias string) transformersTable {
	var (
		TenantIDColumn        = postgres.StringColumn("tenant_id")
		TransfomerIDColumn    = postgres.StringColumn("transfomer_id")
		NameColumn            = postgres.StringColumn("name")
		ConfigColumn          = postgres.StringColumn("config")
		CreatedByUserIDColumn = postgres.StringColumn("created_by_user_id")
		UpdatedByUserIDColumn = postgres.StringColumn("updated_by_user_id")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		allColumns            = postgres.ColumnList{TenantIDColumn, TransfomerIDColumn, NameColumn, ConfigColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, ConfigColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns        = postgres.ColumnList{}
	)

	return transformersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:        TenantIDColumn,
		TransfomerID:    TransfomerIDColumn,
		Name:            NameColumn,
		Config:          ConfigColumn,
		CreatedByUserID: CreatedByUserIDColumn,
		UpdatedByUserID: UpdatedByUserIDColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
