//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TransformerOutput = newTransformerOutputTable("public", "transformer_output", "")

type transformerOutputTable struct {
	postgres.Table

	// Columns
	TenantID      postgres.ColumnString
	TransformerID postgres.ColumnString
	TopicID       postgres.ColumnString
	Config        postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TransformerOutputTable struct {
	transformerOutputTable

	EXCLUDED transformerOutputTable
}

// AS creates new TransformerOutputTable with assigned alias
func (a TransformerOutputTable) AS(alias string) *TransformerOutputTable {
	return newTransformerOutputTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TransformerOutputTable with assigned schema name
func (a TransformerOutputTable) FromSchema(schemaName string) *TransformerOutputTable {
	return newTransformerOutputTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TransformerOutputTable with assigned table prefix
func (a TransformerOutputTable) WithPrefix(prefix string) *TransformerOutputTable {
	return newTransformerOutputTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TransformerOutputTable with assigned table suffix
func (a TransformerOutputTable) WithSuffix(suffix string) *TransformerOutputTable {
	return newTransformerOutputTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTransformerOutputTable(schemaName, tableName, alias string) *TransformerOutputTable {
	return &TransformerOutputTable{
		transformerOutputTable: newTransformerOutputTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newTransformerOutputTableImpl("", "excluded", ""),
	}
}

func newTransformerOutputTableImpl(schemaName, tableName, alias string) transformerOutputTable {
	var (
		TenantIDColumn      = postgres.StringColumn("tenant_id")
		TransformerIDColumn = postgres.StringColumn("transformer_id")
		TopicIDColumn       = postgres.StringColumn("topic_id")
		ConfigColumn        = postgres.StringColumn("config")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{TenantIDColumn, TransformerIDColumn, TopicIDColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{}
	)

	return transformerOutputTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:      TenantIDColumn,
		TransformerID: TransformerIDColumn,
		TopicID:       TopicIDColumn,
		Config:        ConfigColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
