//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TransformerOutputs = newTransformerOutputsTable("public", "transformer_outputs", "")

type transformerOutputsTable struct {
	postgres.Table

	// Columns
	TenantID      postgres.ColumnString
	TransformerID postgres.ColumnString
	TopicID       postgres.ColumnString
	Config        postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TransformerOutputsTable struct {
	transformerOutputsTable

	EXCLUDED transformerOutputsTable
}

// AS creates new TransformerOutputsTable with assigned alias
func (a TransformerOutputsTable) AS(alias string) *TransformerOutputsTable {
	return newTransformerOutputsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TransformerOutputsTable with assigned schema name
func (a TransformerOutputsTable) FromSchema(schemaName string) *TransformerOutputsTable {
	return newTransformerOutputsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TransformerOutputsTable with assigned table prefix
func (a TransformerOutputsTable) WithPrefix(prefix string) *TransformerOutputsTable {
	return newTransformerOutputsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TransformerOutputsTable with assigned table suffix
func (a TransformerOutputsTable) WithSuffix(suffix string) *TransformerOutputsTable {
	return newTransformerOutputsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTransformerOutputsTable(schemaName, tableName, alias string) *TransformerOutputsTable {
	return &TransformerOutputsTable{
		transformerOutputsTable: newTransformerOutputsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newTransformerOutputsTableImpl("", "excluded", ""),
	}
}

func newTransformerOutputsTableImpl(schemaName, tableName, alias string) transformerOutputsTable {
	var (
		TenantIDColumn      = postgres.StringColumn("tenant_id")
		TransformerIDColumn = postgres.StringColumn("transformer_id")
		TopicIDColumn       = postgres.StringColumn("topic_id")
		ConfigColumn        = postgres.StringColumn("config")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{TenantIDColumn, TransformerIDColumn, TopicIDColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{}
	)

	return transformerOutputsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:      TenantIDColumn,
		TransformerID: TransformerIDColumn,
		TopicID:       TopicIDColumn,
		Config:        ConfigColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
