//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Transformer = newTransformerTable("public", "transformer", "")

type transformerTable struct {
	postgres.Table

	// Columns
	TenantID        postgres.ColumnString
	TransfomerID    postgres.ColumnString
	Name            postgres.ColumnString
	Config          postgres.ColumnString
	CreatedByUserID postgres.ColumnString
	UpdatedByUserID postgres.ColumnString
	CreatedAt       postgres.ColumnTimestamp
	UpdatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TransformerTable struct {
	transformerTable

	EXCLUDED transformerTable
}

// AS creates new TransformerTable with assigned alias
func (a TransformerTable) AS(alias string) *TransformerTable {
	return newTransformerTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TransformerTable with assigned schema name
func (a TransformerTable) FromSchema(schemaName string) *TransformerTable {
	return newTransformerTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TransformerTable with assigned table prefix
func (a TransformerTable) WithPrefix(prefix string) *TransformerTable {
	return newTransformerTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TransformerTable with assigned table suffix
func (a TransformerTable) WithSuffix(suffix string) *TransformerTable {
	return newTransformerTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTransformerTable(schemaName, tableName, alias string) *TransformerTable {
	return &TransformerTable{
		transformerTable: newTransformerTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newTransformerTableImpl("", "excluded", ""),
	}
}

func newTransformerTableImpl(schemaName, tableName, alias string) transformerTable {
	var (
		TenantIDColumn        = postgres.StringColumn("tenant_id")
		TransfomerIDColumn    = postgres.StringColumn("transfomer_id")
		NameColumn            = postgres.StringColumn("name")
		ConfigColumn          = postgres.StringColumn("config")
		CreatedByUserIDColumn = postgres.StringColumn("created_by_user_id")
		UpdatedByUserIDColumn = postgres.StringColumn("updated_by_user_id")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		allColumns            = postgres.ColumnList{TenantIDColumn, TransfomerIDColumn, NameColumn, ConfigColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{NameColumn, ConfigColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns        = postgres.ColumnList{}
	)

	return transformerTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:        TenantIDColumn,
		TransfomerID:    TransfomerIDColumn,
		Name:            NameColumn,
		Config:          ConfigColumn,
		CreatedByUserID: CreatedByUserIDColumn,
		UpdatedByUserID: UpdatedByUserIDColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
