//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TransformerInput = newTransformerInputTable("public", "transformer_input", "")

type transformerInputTable struct {
	postgres.Table

	// Columns
	TenantID      postgres.ColumnString
	TransformerID postgres.ColumnString
	TopicID       postgres.ColumnString
	Config        postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TransformerInputTable struct {
	transformerInputTable

	EXCLUDED transformerInputTable
}

// AS creates new TransformerInputTable with assigned alias
func (a TransformerInputTable) AS(alias string) *TransformerInputTable {
	return newTransformerInputTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TransformerInputTable with assigned schema name
func (a TransformerInputTable) FromSchema(schemaName string) *TransformerInputTable {
	return newTransformerInputTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TransformerInputTable with assigned table prefix
func (a TransformerInputTable) WithPrefix(prefix string) *TransformerInputTable {
	return newTransformerInputTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TransformerInputTable with assigned table suffix
func (a TransformerInputTable) WithSuffix(suffix string) *TransformerInputTable {
	return newTransformerInputTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTransformerInputTable(schemaName, tableName, alias string) *TransformerInputTable {
	return &TransformerInputTable{
		transformerInputTable: newTransformerInputTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newTransformerInputTableImpl("", "excluded", ""),
	}
}

func newTransformerInputTableImpl(schemaName, tableName, alias string) transformerInputTable {
	var (
		TenantIDColumn      = postgres.StringColumn("tenant_id")
		TransformerIDColumn = postgres.StringColumn("transformer_id")
		TopicIDColumn       = postgres.StringColumn("topic_id")
		ConfigColumn        = postgres.StringColumn("config")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{TenantIDColumn, TransformerIDColumn, TopicIDColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{}
	)

	return transformerInputTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:      TenantIDColumn,
		TransformerID: TransformerIDColumn,
		TopicID:       TopicIDColumn,
		Config:        ConfigColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
