//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TransformerInputs = newTransformerInputsTable("public", "transformer_inputs", "")

type transformerInputsTable struct {
	postgres.Table

	// Columns
	TenantID      postgres.ColumnString
	TransformerID postgres.ColumnString
	TopicID       postgres.ColumnString
	Config        postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TransformerInputsTable struct {
	transformerInputsTable

	EXCLUDED transformerInputsTable
}

// AS creates new TransformerInputsTable with assigned alias
func (a TransformerInputsTable) AS(alias string) *TransformerInputsTable {
	return newTransformerInputsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TransformerInputsTable with assigned schema name
func (a TransformerInputsTable) FromSchema(schemaName string) *TransformerInputsTable {
	return newTransformerInputsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TransformerInputsTable with assigned table prefix
func (a TransformerInputsTable) WithPrefix(prefix string) *TransformerInputsTable {
	return newTransformerInputsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TransformerInputsTable with assigned table suffix
func (a TransformerInputsTable) WithSuffix(suffix string) *TransformerInputsTable {
	return newTransformerInputsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTransformerInputsTable(schemaName, tableName, alias string) *TransformerInputsTable {
	return &TransformerInputsTable{
		transformerInputsTable: newTransformerInputsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newTransformerInputsTableImpl("", "excluded", ""),
	}
}

func newTransformerInputsTableImpl(schemaName, tableName, alias string) transformerInputsTable {
	var (
		TenantIDColumn      = postgres.StringColumn("tenant_id")
		TransformerIDColumn = postgres.StringColumn("transformer_id")
		TopicIDColumn       = postgres.StringColumn("topic_id")
		ConfigColumn        = postgres.StringColumn("config")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{TenantIDColumn, TransformerIDColumn, TopicIDColumn, ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{ConfigColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{}
	)

	return transformerInputsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TenantID:      TenantIDColumn,
		TransformerID: TransformerIDColumn,
		TopicID:       TopicIDColumn,
		Config:        ConfigColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
