//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Tier = &struct {
	FreeTrial postgres.StringExpression
	Bronze    postgres.StringExpression
	Silver    postgres.StringExpression
	Gold      postgres.StringExpression
	Platinum  postgres.StringExpression
}{
	FreeTrial: postgres.NewEnumValue("free_trial"),
	Bronze:    postgres.NewEnumValue("bronze"),
	Silver:    postgres.NewEnumValue("silver"),
	Gold:      postgres.NewEnumValue("gold"),
	Platinum:  postgres.NewEnumValue("platinum"),
}
